from app.models import db, Choice, environment, SCHEMA


# Adds a demo user, you can add other users here if you want
def seed_choices():
    choice1 = Choice(question_id=1, choice='correct', is_correct=True)
    choice3 = Choice(question_id=1, choice='testing', is_correct=False)
    choice4 = Choice(question_id=1, choice='testing', is_correct=False)
    choice5 = Choice(question_id=1, choice='testing', is_correct=False)
    choice2 = Choice(question_id=2, choice='correct', is_correct=True)
    choice6 = Choice(question_id=2, choice='testing', is_correct=False)
    choice7 = Choice(question_id=2, choice='testing', is_correct=False)
    choice8 = Choice(question_id=2, choice='testing', is_correct=False)
    choice9 = Choice(question_id=3, choice='correct', is_correct=True)
    choice10 = Choice(question_id=3, choice='testing', is_correct=False)
    choice11 = Choice(question_id=3, choice='testing', is_correct=False)
    choice12 = Choice(question_id=3, choice='testing', is_correct=False)
    choice13 = Choice(question_id=4, choice='correct', is_correct=True)
    choice14 = Choice(question_id=4, choice='testing', is_correct=False)
    choice15 = Choice(question_id=4, choice='testing', is_correct=False)
    choice16 = Choice(question_id=4, choice='testing', is_correct=False)
    choice17 = Choice(question_id=5, choice='correct', is_correct=True)
    choice18 = Choice(question_id=5, choice='testing', is_correct=False)
    choice19 = Choice(question_id=5, choice='testing', is_correct=False)
    choice20 = Choice(question_id=5, choice='testing', is_correct=False)
    choice21 = Choice(question_id=6, choice='correct', is_correct=True)
    choice22 = Choice(question_id=6, choice='testing', is_correct=False)
    choice23 = Choice(question_id=6, choice='testing', is_correct=False)
    choice24 = Choice(question_id=6, choice='testing', is_correct=False)
    choice25 = Choice(question_id=7, choice='correct', is_correct=True)
    choice26 = Choice(question_id=7, choice='testing', is_correct=False)
    choice27 = Choice(question_id=7, choice='testing', is_correct=False)
    choice28 = Choice(question_id=7, choice='testing', is_correct=False)
    choice29 = Choice(question_id=8, choice='correct', is_correct=True)
    choice30 = Choice(question_id=8, choice='testing', is_correct=False)
    choice31 = Choice(question_id=8, choice='testing', is_correct=False)
    choice32 = Choice(question_id=8, choice='testing', is_correct=False)
    choice33 = Choice(question_id=9, choice='correct', is_correct=True)
    choice34 = Choice(question_id=9, choice='testing', is_correct=False)
    choice35 = Choice(question_id=9, choice='testing', is_correct=False)
    choice36 = Choice(question_id=9, choice='testing', is_correct=False)
    choice37 = Choice(question_id=10, choice='correct', is_correct=True)
    choice38 = Choice(question_id=10, choice='testing', is_correct=False)
    choice39 = Choice(question_id=10, choice='testing', is_correct=False)
    choice40 = Choice(question_id=10, choice='testing', is_correct=False)
    choice41 = Choice(question_id=11, choice='correct', is_correct=True)
    choice42 = Choice(question_id=11, choice='testing', is_correct=False)
    choice43 = Choice(question_id=11, choice='testing', is_correct=False)
    choice44 = Choice(question_id=11, choice='testing', is_correct=False)
    choice45 = Choice(question_id=12, choice='correct', is_correct=True)
    choice46 = Choice(question_id=12, choice='testing', is_correct=False)
    choice47 = Choice(question_id=12, choice='testing', is_correct=False)
    choice48 = Choice(question_id=12, choice='testing', is_correct=False)
    choice49 = Choice(question_id=13, choice='correct', is_correct=True)
    choice50 = Choice(question_id=13, choice='testing', is_correct=False)
    choice51 = Choice(question_id=13, choice='testing', is_correct=False)
    choice52 = Choice(question_id=13, choice='testing', is_correct=False)
    choice53 = Choice(question_id=14, choice='correct', is_correct=True)
    choice54 = Choice(question_id=14, choice='testing', is_correct=False)
    choice55 = Choice(question_id=14, choice='testing', is_correct=False)
    choice56 = Choice(question_id=14, choice='testing', is_correct=False)
    choice57 = Choice(question_id=15, choice='correct', is_correct=True)
    choice58 = Choice(question_id=15, choice='testing', is_correct=False)
    choice59 = Choice(question_id=15, choice='testing', is_correct=False)
    choice60 = Choice(question_id=15, choice='testing', is_correct=False)
    choice61 = Choice(question_id=16, choice='correct', is_correct=True)
    choice62 = Choice(question_id=16, choice='testing', is_correct=False)
    choice63 = Choice(question_id=16, choice='testing', is_correct=False)
    choice64 = Choice(question_id=16, choice='testing', is_correct=False)




    db.session.add(choice1)
    db.session.add(choice3)
    db.session.add(choice4)
    db.session.add(choice5)
    db.session.add(choice2)
    db.session.add(choice6)
    db.session.add(choice7)
    db.session.add(choice8)
    db.session.add(choice9)
    db.session.add(choice10)
    db.session.add(choice11)
    db.session.add(choice12)
    db.session.add(choice13)
    db.session.add(choice14)
    db.session.add(choice15)
    db.session.add(choice16)
    db.session.add(choice17)
    db.session.add(choice18)
    db.session.add(choice19)
    db.session.add(choice20)
    db.session.add(choice21)
    db.session.add(choice22)
    db.session.add(choice23)
    db.session.add(choice24)
    db.session.add(choice25)
    db.session.add(choice26)
    db.session.add(choice27)
    db.session.add(choice28)
    db.session.add(choice29)
    db.session.add(choice30)
    db.session.add(choice31)
    db.session.add(choice32)
    db.session.add(choice33)
    db.session.add(choice34)
    db.session.add(choice35)
    db.session.add(choice36)
    db.session.add(choice37)
    db.session.add(choice38)
    db.session.add(choice39)
    db.session.add(choice40)
    db.session.add(choice41)
    db.session.add(choice42)
    db.session.add(choice43)
    db.session.add(choice44)
    db.session.add(choice45)
    db.session.add(choice45)
    db.session.add(choice46)
    db.session.add(choice47)
    db.session.add(choice48)
    db.session.add(choice49)
    db.session.add(choice50)
    db.session.add(choice51)
    db.session.add(choice52)
    db.session.add(choice53)
    db.session.add(choice54)
    db.session.add(choice55)
    db.session.add(choice56)
    db.session.add(choice57)
    db.session.add(choice58)
    db.session.add(choice59)
    db.session.add(choice60)
    db.session.add(choice61)
    db.session.add(choice62)
    db.session.add(choice63)
    db.session.add(choice64)
    db.session.commit()


# Uses a raw SQL query to TRUNCATE or DELETE the users table. SQLAlchemy doesn't
# have a built in function to do this. With postgres in production TRUNCATE
# removes all the data from the table, and RESET IDENTITY resets the auto
# incrementing primary key, CASCADE deletes any dependent entities.  With
# sqlite3 in development you need to instead use DELETE to remove all data and
# it will reset the primary keys for you as well.
def undo_choices():
    if environment == "production":
        db.session.execute(f"TRUNCATE table {SCHEMA}.choices RESTART IDENTITY CASCADE;")
    else:
        db.session.execute("DELETE FROM users")

    db.session.commit()
